#!/usr/bin/env bash
set -euo pipefail

# Create a local dev .env with safe defaults for Codex usage

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT_DIR"

if [[ -f .env.local ]]; then
  echo ".env.local already exists; leaving it unchanged."
else
  if [[ -f .env.local.example ]]; then
    cp .env.local.example .env.local
  else
    touch .env.local
  fi
fi

# Generate a strong random JWT secret using Node if available
JWT_SECRET_VAL="$(node -e "console.log(require('crypto').randomBytes(32).toString('base64'))" 2>/dev/null || true)"
if [[ -z "${JWT_SECRET_VAL}" ]]; then
  JWT_SECRET_VAL="change-me-dev-secret"
fi

RESEND_VAL="${RESEND_API_KEY:-re_test_dummy}"
STRIPE_KEY_VAL="${STRIPE_SECRET_KEY:-sk_test_dummy}"
STRIPE_WEBHOOK_VAL="${STRIPE_WEBHOOK_SECRET:-whsec_dummy}"
SITE_URL_VAL="${NEXT_PUBLIC_SITE_URL:-http://localhost:3000}"

cat >> .env.local <<EOF
# --- Generated by scripts/codex-setup.sh (last lines win)
NEXT_PUBLIC_SITE_URL=${SITE_URL_VAL}
SITE_URL=${SITE_URL_VAL}
RESEND_API_KEY=${RESEND_VAL}
STRIPE_SECRET_KEY=${STRIPE_KEY_VAL}
STRIPE_WEBHOOK_SECRET=${STRIPE_WEBHOOK_VAL}
JWT_SECRET=${JWT_SECRET_VAL}
EOF

echo "Wrote/updated .env.local with dev defaults."

